wallpaper {
  monitor = DP-1
  path = /home/user/Pictures/DC_Characters/fixed/
  timeout = 300
}
wallpaper {
  monitor = DP-2
  path = $paper
}
wallpaper {
  monitor = DP-3
  path = $paper
}
splash = false
